### ISSUE TITLE
AttributeError: 'YTick' object has no attribute 'label'

### ISSUE THREAD

**Issue by littleEinstein** [vMeijin/pySmithPlot#41]
while running smith_short_test.py , saw the following error : 

Traceback (most recent call last):
  File "/Users/mayank/Downloads/pySmithPlot-master/testbenches/smith_short_test.py", line 23, in <module>
    ax = pp.subplot(1, 1, 1, projection='smith')
  File "/Users/mayank/Downloads/Sinope_FR1/Dashboard/pySmithPlot-master/.venv/lib/python3.9/site-packages/matplotlib/pyplot.py", line 1437, in subplot
    ax = fig.add_subplot(*args, **kwargs)
  File "/Users/mayank/Downloads/Sinope_FR1/Dashboard/pySmithPlot-master/.venv/lib/python3.9/site-packages/matplotlib/figure.py", line 782, in add_subplot
    ax = projection_class(self, *args, **pkw)
  File "/Users/mayank/Downloads/pySmithPlot-master/smithplot/smithaxes.py", line 374, in __init__
    Axes.__init__(self, *args, **SmithAxes.update_scParams(instance=self, filter_dict=True, reset=False, **kwargs))
  File "/Users/mayank/Downloads/Sinope_FR1/Dashboard/pySmithPlot-master/.venv/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 678, in __init__
    self.clear()
  File "/Users/mayank/Downloads/Sinope_FR1/Dashboard/pySmithPlot-master/.venv/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 1386, in clear
    self.cla()
  File "/Users/mayank/Downloads/pySmithPlot-master/smithplot/smithaxes.py", line 420, in cla
    Axes.cla(self)
  File "/Users/mayank/Downloads/Sinope_FR1/Dashboard/pySmithPlot-master/.venv/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 1395, in cla
    self.__clear()
  File "/Users/mayank/Downloads/Sinope_FR1/Dashboard/pySmithPlot-master/.venv/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 1356, in __clear
    self.yaxis.set_clip_path(self.patch)
  File "/Users/mayank/Downloads/Sinope_FR1/Dashboard/pySmithPlot-master/.venv/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 297, in wrapper
    return func(*args, **kwargs)
  File "/Users/mayank/Downloads/Sinope_FR1/Dashboard/pySmithPlot-master/.venv/lib/python3.9/site-packages/matplotlib/axis.py", line 1111, in set_clip_path
    for child in self.majorTicks + self.minorTicks:
  File "/Users/mayank/Downloads/Sinope_FR1/Dashboard/pySmithPlot-master/.venv/lib/python3.9/site-packages/matplotlib/axis.py", line 591, in __get__
    tick = instance._get_tick(major=False)
  File "/Users/mayank/Downloads/Sinope_FR1/Dashboard/pySmithPlot-master/.venv/lib/python3.9/site-packages/matplotlib/axis.py", line 1562, in _get_tick
    return self._tick_class(self.axes, 0, major=major, **tick_kw)
  File "/Users/mayank/Downloads/Sinope_FR1/Dashboard/pySmithPlot-master/.venv/lib/python3.9/site-packages/matplotlib/axis.py", line 480, in __init__
    trans, va, ha = self._get_text1_transform()
  File "/Users/mayank/Downloads/Sinope_FR1/Dashboard/pySmithPlot-master/.venv/lib/python3.9/site-packages/matplotlib/axis.py", line 492, in _get_text1_transform
    return self.axes.get_yaxis_text1_transform(self._pad)
  File "/Users/mayank/Downloads/pySmithPlot-master/smithplot/smithaxes.py", line 510, in get_yaxis_text1_transform
    font_size = self.yaxis.majorTicks[0].label.get_size()
AttributeError: 'YTick' object has no attribute 'label'

**Comment by almonleo** [comment]
I am running into the same problem. I am using Anaconda/Spyder
Any solution?

**Comment by wenzhao98** [comment]
Can anybody comment on if there is a way to workaround this issue please?

**Comment by Budavaril** [comment]
Same here today.
AttributeError: 'YTick' object has no attribute 'label'. Did you mean: '_label'?

**Comment by Bramhand** [comment]
I got the same problem. Solved it.

I used matplotlib version 3.7.3, which get rid of the error. But new error 'numpy complex......' appear with numpy 1.26 version. I go to numpy.py file and the line where the error shows. I replaced 'np.complex' to complex. Seems like old version of matplotlib does not work with np.complex. I am not fully sure. But this solution works.
  
It now works as it should be.

**Comment by fedetony** [comment]
[Here](https://github.com/vMeijin/pySmithPlot/compare/master...fedetony:pySmithPlot:master) is solved for matplotlib 3.10.3.
